name: CI/CD for PostgreSQL in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: my_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U admin -d my_database"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install psycopg2-binary

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U admin; do
            echo "Waiting for PostgreSQL to start..."
            sleep 3
          done
          echo "PostgreSQL is ready!"

      - name: Import CSV data
        run: python3 scripts/import_csv_to_db.py

      - name: Run KPI queries
        run: python3 scripts/run_queries.py
