name: CI/CD for PostgreSQL in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install psycopg2-binary

      - name: Set up Docker
        run: |
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version
          docker-compose --version

      - name: Start PostgreSQL container
        run: |
          docker-compose up -d
          sleep 10  # Attendre que PostgreSQL démarre

      - name: Check running containers
        run: docker ps -a

      - name: Import CSV data
        run: python3 scripts/import_csv_to_db.py

      - name: Run KPI queries
        run: python3 scripts/run_queries.py




